spring:
  security:
    oauth2:
      resource-server:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/myrealm
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

#keycloak:
#  client-id: myapp
#  client-secret: blah
#  token-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/token
#  issuer-uri: http://localhost:8080/realms/myrealm

static-token: STATIC_AUTH_TOKEN